-- lua/plugins/nvim-tree.lua
-- return {
--     "nvim-tree/nvim-tree.lua",
--     dependencies = {
--         "nvim-tree/nvim-web-devicons",
--     },
--     lazy = false,
--     config = function()
--         require("nvim-tree").setup({
--             disable_netrw = true,
--             hijack_netrw = true,
--             auto_reload_on_write = true,
--             hijack_cursor = true,
--             update_cwd = true,
--             sync_root_with_cwd = true,
--             view = {
--                 width = 35,
--                 side = "left",
--                 mappings = {
--                     list = {
--                         { key = "v", action = "vsplit" },
--                         { key = "s", action = "split" },
--                         { key = "t", action = "tabnew" },
--                         { key = "h", action = "close_node" },
--                     },
--                 },
--             },
--             renderer = {
--                 highlight_git = true,
--                 highlight_opened_files = "all",
--                 icons = {
--                     show = {
--                         git = true,
--                         folder = true,
--                         file = true,
--                         folder_arrow = true,
--                     },
--                 },
--             },
--             diagnostics = {
--                 enable = true,
--                 icons = {
--                     hint = "⚑",
--                     info = "",
--                     warning = "",
--                     error = "✘",
--                 },
--             },
--             git = {
--                 enable = true,
--                 ignore = false,
--                 timeout = 500,
--             },
--             actions = {
--                 open_file = {
--                     quit_on_open = false,
--                 },
--             },
--         })
--
--         -- Keymaps globali
--         vim.keymap.set("n", "<leader>e", ":NvimTreeToggle<CR>", { desc = "Toggle File Tree" })
--         vim.keymap.set("n", "<leader>f", ":NvimTreeFindFile<CR>", { desc = "Focus current file in tree" })
--     end,
-- }
